# Generated by Django 3.2.12 on 2022-03-07 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0002_auto_20220307_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал заметку'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна (да/нет)'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.projects', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='text',
            field=models.CharField(max_length=256, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Название проекта'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Участники проекта'),
        ),
    ]
